#cloud-config
# vim: syntax=yaml
package_update: True
package_upgrade: True
apt:
  primary:
    - arches: [default]
      search_dns: True
packages:
  - apt-transport-https
  - gnupg2
  - gnutls-bin
  - ocserv
  - ssg-base
  - ssg-debderived
  - ssg-debian
  - ssg-nondebian
  - ssg-applications
  - auditd
  - audispd-plugins
  - iptables-persistent
  - software-properties-common
write_files:
  - owner: root:root
    path: /etc/logrotate.d/auditd
    content: |
      /var/log/audit/audit.log {
          daily
          rotate 7
          copytruncate
          compress
          missingok
          notifempty
          sharedscripts
          postrotate
          invoke-rc.d auditd restart
          endscript
      }
  - owner: root:root
    path: /etc/audit/audit.rules
    content: |
      -w /etc/passwd -p wa -k
      -w /etc/group -p wa -k 
      -w /etc/gshadow -p wa -k 
      -w /etc/shadow -p wa -k 
      -w /etc/security/opasswd -p wa -k identity
      -a always,exit -F arch=b64 -S execve -C uid!=euid -F key=execpriv 
      -a always,exit -F arch=b64 -S execve -C gid!=egid -F key=execpriv 
      -a always,exit -F path=/bin/su -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-priv_change 
      -a always,exit -F path=/bin/su -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-priv_change 
      -a always,exit -F path=/bin/umount -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-mount
      -a always,exit -F path=/usr/bin/ssh-agent -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-ssh
      -a always,exit -F path=/usr/lib/openssh/ssh-keysign -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-ssh
      -w /sbin/insmod -p x -k modules
      -w /sbin/rmmod -p x -k modules
      -w /sbin/modprobe -p x -k modules
      -w /bin/kmod -p x -k modules
      -a always,exit -F arch=b64 -S setxattr -F auid>=1000 -F auid!=4294967295 -k perm_mod
      -a always,exit -F arch=b64 -S setxattr -F auid=0 -k perm_mod 
      -a always,exit -F arch=b64 -S lsetxattr -F auid>=1000 -F auid!=4294967295 -k perm_mod
      -a always,exit -F arch=b64 -S lsetxattr -F auid=0 -k perm_mod 
      -a always,exit -F arch=b64 -S fsetxattr -F auid>=1000 -F auid!=4294967295 -k perm_mod
      -a always,exit -F arch=b64 -S fsetxattr -F auid=0 -k perm_mod
      -a always,exit -F arch=b64 -S removexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod
      -a always,exit -F arch=b64 -S removexattr -F auid=0 -k perm_mod 
      -a always,exit -F arch=b64 -S lremovexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod
      -a always,exit -F arch=b64 -S lremovexattr -F auid=0 -k perm_mod
      -a always,exit -F arch=b64 -S fremovexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod
      -a always,exit -F arch=b64 -S fremovexattr -F auid=0 -k perm_mod
      -a always,exit -F arch=b64 -S chown -F auid>=1000 -F auid!=4294967295 -k perm_chng
      -a always,exit -F arch=b64 -S fchown -F auid>=1000 -F auid!=4294967295 -k perm_chng
      -a always,exit -F arch=b64 -S fchownat -F auid>=1000 -F auid!=4294967295 -k perm_chng
      -a always,exit -F arch=b64 -S lchown -F auid>=1000 -F auid!=4294967295 -k perm_chng
      -a always,exit -F arch=b64 -S chmod -F auid>=1000 -F auid!=4294967295 -k perm_chng
      -a always,exit -F arch=b64 -S fchmod -F auid>=1000 -F auid!=4294967295 -k perm_chng
      -a always,exit -F arch=b64 -S fchmodat -F auid>=1000 -F auid!=4294967295 -k perm_chng
      -a always,exit -F arch=b64 -S open -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k perm_access
      -a always,exit -F arch=b64 -S open -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k perm_access
      -a always,exit -F arch=b64 -S truncate -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k perm_access
      -a always,exit -F arch=b64 -S truncate -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k perm_access
      -a always,exit -F arch=b64 -S ftruncate -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k perm_access
      -a always,exit -F arch=b64 -S ftruncate -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k perm_access
      -a always,exit -F arch=b64 -S creat -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k perm_access
      -a always,exit -F arch=b64 -S creat -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k perm_access
      -a always,exit -F arch=b64 -S openat -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k perm_access
      -a always,exit -F arch=b64 -S openat -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k perm_access
      -a always,exit -F arch=b64 -S open_by_handle_at -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k perm_access
      -a always,exit -F arch=b64 -S open_by_handle_at -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k perm_access
      -a always,exit -F path=/usr/bin/sudo -F perm=x -F auid>=1000 -F auid!=4294967295 -k priv_cmd
      -a always,exit -F path=/usr/bin/sudoedit -F perm=x -F auid>=1000 -F auid!=4294967295 -k priv_cmd
      -a always,exit -F path=/usr/bin/chsh -F perm=x -F auid>=1000 -F auid!=4294967295 -k priv_cmd
      -a always,exit -F path=/usr/bin/newgrp -F perm=x -F auid>=1000 -F auid!=4294967295 -k priv_cmd
      -a always,exit -F path=/sbin/apparmor_parser -F perm=x -F auid>=1000 -F auid!=4294967295 -k perm_chng
      -a always,exit -F path=/usr/bin/setfacl -F perm=x -F auid>=1000 -F auid!=4294967295 -k perm_chng
      -a always,exit -F path=/usr/bin/chacl -F perm=x -F auid>=1000 -F auid!=4294967295 -k perm_chng
      -w /var/log/tallylog -p wa -k logins
      -w /var/log/faillog -p wa -k logins
      -w /var/log/lastlog -p wa -k logins
      -a always,exit -F path=/usr/bin/passwd -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-passwd
      -a always,exit -F path=/sbin/unix_update -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-unix-update
      -a always,exit -F path=/usr/bin/gpasswd -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-gpasswd
      -a always,exit -F path=/usr/bin/chage -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-chage
      -a always,exit -F path=/usr/sbin/usermod -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-usermod
      -a always,exit -F path=/usr/bin/crontab -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-crontab
      -a always,exit -F path=/usr/sbin/pam_timestamp_check -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-pam_timestamp_check
      -a always,exit -F arch=b64 -S init_module -F auid>=1000 -F auid!=4294967295 -k module_chng
      -a always,exit -F arch=b64 -S finit_module -F auid>=1000 -F auid!=4294967295 -k module_chng
      -a always,exit -F arch=b64 -S delete_module -F auid>=1000 -F auid!=4294967295 -k module_chng
      -a always,exit -F path=/usr/bin/chcon -F perm=x -F auid>=1000 -F auid!=4294967295 -k perm_chng
      -a always,exit -F path=/usr/bin/chfn -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-gpasswd
  - owner: root:root
    path: /etc/pam.d/common-auth
    content: |
      auth    [success=1 default=ignore]      pam_unix.so 
      auth    required                        pam_deny.so
      auth    required                        pam_tally2.so    onerr=fail deny=3 unlock_time=3600
      auth    required                        pam_permit.so
      auth    required                        pam_faildelay.so    delay=4000000
      auth sufficient pam_timestamp.so timestamp_timeout=86400
  - path: /etc/cron.d/letsencrypt_renew
    content: 15 3 * * * /usr/bin/certbot renew --quiet
  - path: /etc/ssh/sshd_config
    content: |
      Port 22
      Protocol 2
      UsePrivilegeSeparation yes
      KeyRegenerationInterval 3600
      ServerKeyBits 1024
      SyslogFacility AUTH
      LogLevel INFO
      LoginGraceTime 120
      MaxAuthTries 6
      MaxSessions 10
      PermitRootLogin no
      StrictModes yes
      RSAAuthentication yes
      PubkeyAuthentication yes
      IgnoreRhosts yes
      RhostsRSAAuthentication no
      HostbasedAuthentication no
      PermitEmptyPasswords no
      ChallengeResponseAuthentication no
      X11Forwarding yes
      X11DisplayOffset 10
      PrintMotd no
      PrintLastLog yes
      TCPKeepAlive yes
      AcceptEnv LANG LC_*
      Subsystem sftp /usr/lib/openssh/sftp-server
      UsePAM yes
      Banner "You are accessing a U.S. Government (USG) Information System (IS) that is provided for USG-authorized use only. By using this IS (which includes any device attached to this IS), you consent to the following conditions: The USG routinely intercepts and monitors communications on this IS for purposes including, but not limited to, penetration testing, COMSEC monitoring, network operations and defense, personnel misconduct (PM), law enforcement (LE), and counterintelligence (CI) investigations. At any time, the USG may inspect and seize data stored on this IS. Communications using, or data stored on, this IS are not private, are subject to routine monitoring, interception, and search, and may be disclosed or used for any USG authorized purpose. This IS includes security measures (e.g., authentication and access controls) to protect USG interests--not for your personal benefit or privacy. Notwithstanding the above, using this IS does not constitute consent to PM, LE or CI investigative searching or monitoring of the content of privileged communications, or work product, related to personal representation or services by attorneys, psychotherapists, or clergy, and their assistants. Such communications and work product are private and confidential. See User Agreement for details."
runcmd:
  - sudo snap install core
  - sudo snap refresh core
  - sudo snap install --classic certbot
  - sudo ln -s /snap/bin/certbot /usr/bin/certbot
  - sudo certbot certonly --standalone -n -d ${fqdn} --hsts --email ${owner} --agree-tos
  - sed -i '/server-cert/a server-cert = /etc/letsencrypt/live/${fqdn}/fullchain.pem' /tmp/ocserv.conf
  - sed -i '/server-key/a server-key = /etc/letsencrypt/live/${fqdn}/privkey.pem' /tmp/ocserv.conf
  - sed -i '/ca-cert/a ca-cert = /etc/letsencrypt/live/${fqdn}/chain.pem' /tmp/ocserv.conf
  - sudo mv -f /tmp/ocserv.conf /etc/ocserv/ocserv.conf 
  - sudo mv -f /tmp/ocserv.socket /lib/systemd/system/ocserv.socket
  - echo "${password}" | sudo ocpasswd -c /etc/ocserv/ocpasswd vpnuser
  - sudo systemctl restart ocserv
  - iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
  - dpkg-reconfigure iptables-persistent
  - sudo apt-get -y clean
  - sudo apt-get -y autoremove --purge
  - echo "maxpoll = 17" >> /etc/ntp.conf
  - systemctl restart ntp
  - sed -i 's|#net.ipv4.ip_forward=1|net.ipv4.ip_forward = 1|g' /etc/sysctl.conf
  - sudo sysctl -p > /dev/null
  - sed -i 's|max_log_file_action = ROTATE|max_log_file_action = SYSLOG|g' /etc/audit/auditd.conf
  - sed -i 's|disk_full_action = SUSPEND|disk_full_action = HALT|g' /etc/audit/auditd.conf
  - systemctl restart auditd.service
power_state:
  mode: reboot
  timeout: 120